# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2026.08.14
group=com.nosiphus.furniture
java_version=21

# Common - NFM
minecraft_version=1.21.1
mod_name=Nosiphus Furniture Mod
mod_author=Nosiphus
mod_id=nfm
license=GPLv3
credits=MrCrayFish, Nosiphus, Ocelot, meappy
description=Nosiphus Furniture Mod is an addon to MrCrayFish's Furniture Mod that readds old furniture.
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Common - CFM
cfm_mod_name=MrCrayFish's Furniture Mod
cfm_mod_author=MrCrayFish, Nosiphus
cfm_mod_id=cfm
cfm_credits=The people who helped me when I first started creating mods. I wouldn't be here without them!
cfm_description=MrCrayfish's Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates. Ported by Nosiphus as part of Nosiphus Furniture Mod.

# Fabric
fabric_version=0.116.5+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.220
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# JEI
jei_version=19.21.0.247

# WTHIT & Bad Packets
wthit_version=12.10.2
badpackets_version=0.8.2