# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2026.09.12
group=com.nosiphus.furniture
java_version=17

# Common - NFM
minecraft_version=1.20.1
mod_name=Nosiphus Furniture Mod
mod_author=Nosiphus
mod_id=nfm
license=GPLv3
credits=MrCrayFish, Nosiphus, Ocelot, meappy
description=Nosiphus Furniture Mod is an addon to MrCrayFish's Furniture Mod that readds old furniture.
minecraft_version_range=[1.20.1, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

#Common - CFM
cfm_mod_name=MrCrayFish's Furniture Mod
cfm_mod_author=MrCrayFish, Nosiphus
cfm_mod_id=cfm
cfm_credits=The people who helped me when I first started creating mods. I wouldn't be here without them!
cfm_description=MrCrayfish's Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates. Ported by Nosiphus as part of Nosiphus Furniture Mod.

# Fabric
fabric_version=0.92.3+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.3.10
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#JEI
jei_version=15.20.0.123

#WTHIT
wthit_version=8.21.1
badpackets_version=0.4.3
