package com.nosiphus.furniture.core;

import com.mrcrayfish.furniture.tileentity.BedsideCabinetBlockEntity;
import com.mrcrayfish.furniture.tileentity.CabinetBlockEntity;
import com.mrcrayfish.furniture.tileentity.DeskCabinetBlockEntity;
import com.mrcrayfish.furniture.tileentity.KitchenDrawerBlockEntity;
import com.nosiphus.furniture.Reference;
import com.nosiphus.furniture.blockentity.*;
import com.nosiphus.furniture.blockentity.yogmod.YogDigitalClockBlockEntity;
import com.nosiphus.furniture.blockentity.yogmod.YogModernKitchenSinkBlockEntity;
import com.nosiphus.furniture.cfm.CFMModBlocks;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import javax.annotation.Nullable;
import java.util.function.Supplier;

public class ModBlockEntities {

    public static final DeferredRegister<BlockEntityType<?>> BLOCK_ENTITIES = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, Reference.MOD_ID);

    public static final RegistryObject<BlockEntityType<BathBlockEntity>> BATH = register("bath", BathBlockEntity::new, () -> new Block[]{ModBlocks.BATH_LIGHT.get(), ModBlocks.BATH_DARK.get()});
    public static final RegistryObject<BlockEntityType<BinBlockEntity>> BIN = register("bin", BinBlockEntity::new, () -> new Block[]{ModBlocks.BIN_LIGHT.get(), ModBlocks.BIN_DARK.get()});
    public static final RegistryObject<BlockEntityType<BedsideCabinetBlockEntity>> BEDSIDE_CABINET = register("bedside_cabinet", BedsideCabinetBlockEntity::new, () -> new Block[]{ModBlocks.BEDSIDE_CABINET_STONE.get(), ModBlocks.BEDSIDE_CABINET_ANDESITE.get(), ModBlocks.BEDSIDE_CABINET_DIORITE.get(), ModBlocks.BEDSIDE_CABINET_GRANITE.get(), ModBlocks.BEDSIDE_CABINET_BLACKSTONE.get(), ModBlocks.BEDSIDE_CABINET_DEEPSLATE.get(), ModBlocks.BEDSIDE_CABINET_WHITE_MODERN.get(), ModBlocks.BEDSIDE_CABINET_ORANGE_MODERN.get(), ModBlocks.BEDSIDE_CABINET_MAGENTA_MODERN.get(), ModBlocks.BEDSIDE_CABINET_LIGHT_BLUE_MODERN.get(), ModBlocks.BEDSIDE_CABINET_YELLOW_MODERN.get(), ModBlocks.BEDSIDE_CABINET_LIME_MODERN.get(), ModBlocks.BEDSIDE_CABINET_PINK_MODERN.get(), ModBlocks.BEDSIDE_CABINET_GRAY_MODERN.get(), ModBlocks.BEDSIDE_CABINET_LIGHT_GRAY_MODERN.get(), ModBlocks.BEDSIDE_CABINET_CYAN_MODERN.get(), ModBlocks.BEDSIDE_CABINET_PURPLE_MODERN.get(), ModBlocks.BEDSIDE_CABINET_BLUE_MODERN.get(), ModBlocks.BEDSIDE_CABINET_BROWN_MODERN.get(), ModBlocks.BEDSIDE_CABINET_GREEN_MODERN.get(), ModBlocks.BEDSIDE_CABINET_RED_MODERN.get(), ModBlocks.BEDSIDE_CABINET_BLACK_MODERN.get()});
    public static final RegistryObject<BlockEntityType<BirdBathBlockEntity>> BIRD_BATH = register("bird_bath", BirdBathBlockEntity::new, () -> new Block[]{ModBlocks.BIRD_BATH_STONE.get(), ModBlocks.BIRD_BATH_ANDESITE.get(), ModBlocks.BIRD_BATH_DIORITE.get(), ModBlocks.BIRD_BATH_GRANITE.get(), ModBlocks.BIRD_BATH_BLACKSTONE.get(), ModBlocks.BIRD_BATH_DEEPSLATE.get()});
    public static final RegistryObject<BlockEntityType<CabinetBlockEntity>> CABINET = register("cabinet", CabinetBlockEntity::new, () -> new Block[]{ModBlocks.CABINET_STONE.get(), ModBlocks.CABINET_ANDESITE.get(), ModBlocks.CABINET_DIORITE.get(), ModBlocks.CABINET_GRANITE.get(), ModBlocks.CABINET_BLACKSTONE.get(), ModBlocks.CABINET_DEEPSLATE.get(), ModBlocks.CABINET_WHITE_MODERN.get(), ModBlocks.CABINET_ORANGE_MODERN.get(), ModBlocks.CABINET_MAGENTA_MODERN.get(), ModBlocks.CABINET_LIGHT_BLUE_MODERN.get(), ModBlocks.CABINET_YELLOW_MODERN.get(), ModBlocks.CABINET_LIME_MODERN.get(), ModBlocks.CABINET_PINK_MODERN.get(), ModBlocks.CABINET_GRAY_MODERN.get(), ModBlocks.CABINET_LIGHT_GRAY_MODERN.get(), ModBlocks.CABINET_CYAN_MODERN.get(), ModBlocks.CABINET_PURPLE_MODERN.get(), ModBlocks.CABINET_BLUE_MODERN.get(), ModBlocks.CABINET_BROWN_MODERN.get(), ModBlocks.CABINET_GREEN_MODERN.get(), ModBlocks.CABINET_RED_MODERN.get(), ModBlocks.CABINET_BLACK_MODERN.get(), ModBlocks.TELEVISION_STAND_WHITE.get(), ModBlocks.TELEVISION_STAND_ORANGE.get(), ModBlocks.TELEVISION_STAND_MAGENTA.get(), ModBlocks.TELEVISION_STAND_LIGHT_BLUE.get(), ModBlocks.TELEVISION_STAND_YELLOW.get(), ModBlocks.TELEVISION_STAND_LIME.get(), ModBlocks.TELEVISION_STAND_PINK.get(), ModBlocks.TELEVISION_STAND_GRAY.get(), ModBlocks.TELEVISION_STAND_LIGHT_GRAY.get(), ModBlocks.TELEVISION_STAND_CYAN.get(), ModBlocks.TELEVISION_STAND_PURPLE.get(), ModBlocks.TELEVISION_STAND_BLUE.get(), ModBlocks.TELEVISION_STAND_BROWN.get(), ModBlocks.TELEVISION_STAND_GREEN.get(), ModBlocks.TELEVISION_STAND_RED.get(), ModBlocks.TELEVISION_STAND_BLACK.get()});
    public static final RegistryObject<BlockEntityType<ChoppingBoardBlockEntity>> CHOPPING_BOARD = register("chopping_board", ChoppingBoardBlockEntity::new, () -> new Block[]{ModBlocks.CHOPPING_BOARD_OAK.get(), ModBlocks.CHOPPING_BOARD_SPRUCE.get(), ModBlocks.CHOPPING_BOARD_BIRCH.get(), ModBlocks.CHOPPING_BOARD_JUNGLE.get(), ModBlocks.CHOPPING_BOARD_ACACIA.get(), ModBlocks.CHOPPING_BOARD_DARK_OAK.get(), ModBlocks.CHOPPING_BOARD_CRIMSON.get(), ModBlocks.CHOPPING_BOARD_WARPED.get(), ModBlocks.CHOPPING_BOARD_MANGROVE.get(), ModBlocks.CHOPPING_BOARD_CHERRY.get()});
    public static final RegistryObject<BlockEntityType<CookieJarBlockEntity>> COOKIE_JAR = register("cookie_jar", CookieJarBlockEntity::new, () -> new Block[]{ModBlocks.COOKIE_JAR.get()});
    public static final RegistryObject<BlockEntityType<DeskCabinetBlockEntity>> DESK_CABINET = register("desk_cabinet", DeskCabinetBlockEntity::new, () -> new Block[]{ModBlocks.DESK_CABINET_STONE.get(), ModBlocks.DESK_CABINET_ANDESITE.get(), ModBlocks.DESK_CABINET_DIORITE.get(), ModBlocks.DESK_CABINET_GRANITE.get(), ModBlocks.DESK_CABINET_BLACKSTONE.get(), ModBlocks.DESK_CABINET_DEEPSLATE.get(), ModBlocks.DESK_CABINET_WHITE_MODERN.get(), ModBlocks.DESK_CABINET_ORANGE_MODERN.get(), ModBlocks.DESK_CABINET_MAGENTA_MODERN.get(), ModBlocks.DESK_CABINET_LIGHT_BLUE_MODERN.get(), ModBlocks.DESK_CABINET_YELLOW_MODERN.get(), ModBlocks.DESK_CABINET_LIME_MODERN.get(), ModBlocks.DESK_CABINET_PINK_MODERN.get(), ModBlocks.DESK_CABINET_GRAY_MODERN.get(), ModBlocks.DESK_CABINET_LIGHT_GRAY_MODERN.get(), ModBlocks.DESK_CABINET_CYAN_MODERN.get(), ModBlocks.DESK_CABINET_PURPLE_MODERN.get(), ModBlocks.DESK_CABINET_BLUE_MODERN.get(), ModBlocks.DESK_CABINET_BROWN_MODERN.get(), ModBlocks.DESK_CABINET_GREEN_MODERN.get(), ModBlocks.DESK_CABINET_RED_MODERN.get(), ModBlocks.DESK_CABINET_BLACK_MODERN.get()});
    public static final RegistryObject<BlockEntityType<DigitalClockBlockEntity>> DIGITAL_CLOCK = register("digital_clock", DigitalClockBlockEntity::new, () -> new Block[]{ModBlocks.DIGITAL_CLOCK_WHITE.get(), ModBlocks.DIGITAL_CLOCK_ORANGE.get(), ModBlocks.DIGITAL_CLOCK_MAGENTA.get(), ModBlocks.DIGITAL_CLOCK_LIGHT_BLUE.get(), ModBlocks.DIGITAL_CLOCK_YELLOW.get(), ModBlocks.DIGITAL_CLOCK_LIME.get(), ModBlocks.DIGITAL_CLOCK_PINK.get(), ModBlocks.DIGITAL_CLOCK_GRAY.get(), ModBlocks.DIGITAL_CLOCK_LIGHT_GRAY.get(), ModBlocks.DIGITAL_CLOCK_CYAN.get(), ModBlocks.DIGITAL_CLOCK_PURPLE.get(), ModBlocks.DIGITAL_CLOCK_BLUE.get(), ModBlocks.DIGITAL_CLOCK_BROWN.get(), ModBlocks.DIGITAL_CLOCK_GREEN.get(), ModBlocks.DIGITAL_CLOCK_RED.get(), ModBlocks.DIGITAL_CLOCK_BLACK.get()});
    public static final RegistryObject<BlockEntityType<DishwasherBlockEntity>> DISHWASHER = register("dishwasher", DishwasherBlockEntity::new, () -> new Block[]{ModBlocks.DISHWASHER_LIGHT.get(), ModBlocks.DISHWASHER_DARK.get()});
    public static final RegistryObject<BlockEntityType<FireAlarmBlockEntity>> FIRE_ALARM = register("fire_alarm", FireAlarmBlockEntity::new, () -> new Block[]{ModBlocks.FIRE_ALARM.get()});
    public static final RegistryObject<BlockEntityType<KitchenDrawerBlockEntity>> KITCHEN_DRAWER = register("kitchen_drawer", KitchenDrawerBlockEntity::new, () -> new Block[]{ModBlocks.KITCHEN_DRAWER_WHITE_MODERN.get(), ModBlocks.KITCHEN_DRAWER_ORANGE_MODERN.get(), ModBlocks.KITCHEN_DRAWER_MAGENTA_MODERN.get(), ModBlocks.KITCHEN_DRAWER_LIGHT_BLUE_MODERN.get(), ModBlocks.KITCHEN_DRAWER_YELLOW_MODERN.get(), ModBlocks.KITCHEN_DRAWER_LIME_MODERN.get(), ModBlocks.KITCHEN_DRAWER_PINK_MODERN.get(), ModBlocks.KITCHEN_DRAWER_GRAY_MODERN.get(), ModBlocks.KITCHEN_DRAWER_LIGHT_GRAY_MODERN.get(), ModBlocks.KITCHEN_DRAWER_CYAN_MODERN.get(), ModBlocks.KITCHEN_DRAWER_PURPLE_MODERN.get(), ModBlocks.KITCHEN_DRAWER_BLUE_MODERN.get(), ModBlocks.KITCHEN_DRAWER_BROWN_MODERN.get(), ModBlocks.KITCHEN_DRAWER_GREEN_MODERN.get(), ModBlocks.KITCHEN_DRAWER_RED_MODERN.get(), ModBlocks.KITCHEN_DRAWER_BLACK_MODERN.get()});
    public static final RegistryObject<BlockEntityType<MicrowaveBlockEntity>> MICROWAVE = register("microwave", MicrowaveBlockEntity::new, () -> new Block[]{ModBlocks.MICROWAVE_LIGHT.get(), ModBlocks.MICROWAVE_DARK.get()});
    public static final RegistryObject<BlockEntityType<ModernKitchenSinkBlockEntity>> MODERN_KITCHEN_SINK = register("modern_kitchen_sink", ModernKitchenSinkBlockEntity::new, () -> new Block[]{ModBlocks.KITCHEN_SINK_WHITE_MODERN.get(), ModBlocks.KITCHEN_SINK_ORANGE_MODERN.get(), ModBlocks.KITCHEN_SINK_MAGENTA_MODERN.get(), ModBlocks.KITCHEN_SINK_LIGHT_BLUE_MODERN.get(), ModBlocks.KITCHEN_SINK_YELLOW_MODERN.get(), ModBlocks.KITCHEN_SINK_LIME_MODERN.get(), ModBlocks.KITCHEN_SINK_PINK_MODERN.get(), ModBlocks.KITCHEN_SINK_GRAY_MODERN.get(), ModBlocks.KITCHEN_SINK_LIGHT_GRAY_MODERN.get(), ModBlocks.KITCHEN_SINK_CYAN_MODERN.get(), ModBlocks.KITCHEN_SINK_PURPLE_MODERN.get(), ModBlocks.KITCHEN_SINK_BLUE_MODERN.get(), ModBlocks.KITCHEN_SINK_BROWN_MODERN.get(), ModBlocks.KITCHEN_SINK_GREEN_MODERN.get(), ModBlocks.KITCHEN_SINK_RED_MODERN.get(), ModBlocks.KITCHEN_SINK_BLACK_MODERN.get(), CFMModBlocks.KITCHEN_SINK_LIGHT_CHERRY.get(), CFMModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_CHERRY.get(), CFMModBlocks.KITCHEN_SINK_DARK_CHERRY.get(), CFMModBlocks.KITCHEN_SINK_DARK_STRIPPED_CHERRY.get()});
    public static final RegistryObject<BlockEntityType<OvenBlockEntity>> OVEN = register("oven", OvenBlockEntity::new, () -> new Block[]{ModBlocks.OVEN_LIGHT.get(), ModBlocks.OVEN_DARK.get()});
    public static final RegistryObject<BlockEntityType<PlateBlockEntity>> PLATE = register("plate", PlateBlockEntity::new, () -> new Block[]{ModBlocks.PLATE.get()});
    public static final RegistryObject<BlockEntityType<PrinterBlockEntity>> PRINTER = register("printer", PrinterBlockEntity::new, () -> new Block[]{ModBlocks.PRINTER.get()});
    public static final RegistryObject<BlockEntityType<SinkBlockEntity>> SINK = register("sink", SinkBlockEntity::new, () -> new Block[]{ModBlocks.SINK_LIGHT.get(), ModBlocks.SINK_DARK.get()});
    public static final RegistryObject<BlockEntityType<ShowerHeadBlockEntity>> SHOWER_HEAD = register("shower_head", ShowerHeadBlockEntity::new, () -> new Block[]{ModBlocks.SHOWER_HEAD_LIGHT.get(), ModBlocks.SHOWER_HEAD_DARK.get()});
    public static final RegistryObject<BlockEntityType<StereoBlockEntity>> STEREO = register("stereo", StereoBlockEntity::new, () -> new Block[]{ModBlocks.STEREO.get()});
    public static final RegistryObject<BlockEntityType<ToasterBlockEntity>> TOASTER = register("toaster", ToasterBlockEntity::new, () -> new Block[]{ModBlocks.TOASTER_LIGHT.get(), ModBlocks.TOASTER_DARK.get()});
    public static final RegistryObject<BlockEntityType<ToiletBlockEntity>> TOILET = register("toilet", ToiletBlockEntity::new, () -> new Block[]{ModBlocks.TOILET_LIGHT.get(), ModBlocks.TOILET_DARK.get()});
    public static final RegistryObject<BlockEntityType<WallCabinetBlockEntity>> WALL_CABINET = register("wall_cabinet", WallCabinetBlockEntity::new, () -> new Block[]{ModBlocks.WALL_CABINET_WHITE.get(), ModBlocks.WALL_CABINET_ORANGE.get(), ModBlocks.WALL_CABINET_MAGENTA.get(), ModBlocks.WALL_CABINET_LIGHT_BLUE.get(), ModBlocks.WALL_CABINET_YELLOW.get(), ModBlocks.WALL_CABINET_LIME.get(), ModBlocks.WALL_CABINET_PINK.get(), ModBlocks.WALL_CABINET_GRAY.get(), ModBlocks.WALL_CABINET_LIGHT_GRAY.get(), ModBlocks.WALL_CABINET_CYAN.get(), ModBlocks.WALL_CABINET_PURPLE.get(), ModBlocks.WALL_CABINET_BLUE.get(), ModBlocks.WALL_CABINET_BROWN.get(), ModBlocks.WALL_CABINET_GREEN.get(), ModBlocks.WALL_CABINET_RED.get(), ModBlocks.WALL_CABINET_BLACK.get()});
    public static final RegistryObject<BlockEntityType<WashingMachineBlockEntity>> WASHING_MACHINE = register("washing_machine", WashingMachineBlockEntity::new, () -> new Block[]{ModBlocks.WASHING_MACHINE_LIGHT.get(), ModBlocks.WASHING_MACHINE_DARK.get()});
    public static final RegistryObject<BlockEntityType<WaterTankBlockEntity>> WATER_TANK = register("water_tank", WaterTankBlockEntity::new, () -> new Block[]{ModBlocks.OAK_WATER_TANK.get(), ModBlocks.SPRUCE_WATER_TANK.get(), ModBlocks.BIRCH_WATER_TANK.get(), ModBlocks.JUNGLE_WATER_TANK.get(), ModBlocks.ACACIA_WATER_TANK.get(), ModBlocks.DARK_OAK_WATER_TANK.get(), ModBlocks.CRIMSON_WATER_TANK.get(), ModBlocks.WARPED_WATER_TANK.get(), ModBlocks.MANGROVE_WATER_TANK.get(), ModBlocks.CHERRY_WATER_TANK.get()});

    public static final RegistryObject<BlockEntityType<BedsideCabinetBlockEntity>> YOGMOD_BEDSIDE_CABINET = registerOptional("yogmod", "yogmod_bedside_cabinet", BedsideCabinetBlockEntity::new, () -> new Block[]{ModBlocks.BEDSIDE_CABINET_BEIGE_MODERN.get()});
    public static final RegistryObject<BlockEntityType<CabinetBlockEntity>> YOGMOD_CABINET = registerOptional("yogmod", "yogmod_cabinet", CabinetBlockEntity::new, () -> new Block[]{ModBlocks.CABINET_BEIGE_MODERN.get(), ModBlocks.TELEVISION_STAND_BEIGE.get()});
    public static final RegistryObject<BlockEntityType<DeskCabinetBlockEntity>> YOGMOD_DESK_CABINET = registerOptional("yogmod", "yogmod_desk_cabinet", DeskCabinetBlockEntity::new, () -> new Block[]{ModBlocks.DESK_CABINET_BEIGE_MODERN.get()});
    public static final RegistryObject<BlockEntityType<YogDigitalClockBlockEntity>> YOGMOD_DIGITAL_CLOCK = registerOptional("yogmod", "yogmod_digital_clock", YogDigitalClockBlockEntity::new, () -> new Block[]{ModBlocks.DIGITAL_CLOCK_BEIGE.get()});
    public static final RegistryObject<BlockEntityType<KitchenDrawerBlockEntity>> YOGMOD_KITCHEN_DRAWER = registerOptional("yogmod", "yogmod_kitchen_drawer", KitchenDrawerBlockEntity::new, () -> new Block[]{ModBlocks.KITCHEN_DRAWER_BEIGE_MODERN.get()});
    public static final RegistryObject<BlockEntityType<YogModernKitchenSinkBlockEntity>> YOGMOD_MODERN_KITCHEN_SINK = registerOptional("yogmod", "yogmod_modern_kitchen_sink", YogModernKitchenSinkBlockEntity::new, () -> new Block[]{ModBlocks.KITCHEN_SINK_BEIGE_MODERN.get()});
    public static final RegistryObject<BlockEntityType<WallCabinetBlockEntity>> YOGMOD_WALL_CABINET = registerOptional("yogmod", "yogmod_wall_cabinet", WallCabinetBlockEntity::new, () -> new Block[]{ModBlocks.WALL_CABINET_BEIGE.get()});

    private static <T extends BlockEntity> RegistryObject<BlockEntityType<T>> register(String name, BlockEntityType.BlockEntitySupplier<T> supplier, Supplier<Block[]> validBlocksSupplier)
    {
        return BLOCK_ENTITIES.register(name, () -> BlockEntityType.Builder.of(supplier, validBlocksSupplier.get()).build(null));
    }

    @Nullable
    private static <T extends BlockEntity> RegistryObject<BlockEntityType<T>> registerOptional(String modID, String name, BlockEntityType.BlockEntitySupplier<T> supplier, Supplier<Block[]> validBlocksSupplier)
    {
        if(ModList.get().isLoaded(modID)) {
            return BLOCK_ENTITIES.register(name, () -> BlockEntityType.Builder.of(supplier, validBlocksSupplier.get()).build(null));
        }
        return null;
    }

}
