modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Nosiphus/nosiphus-furniture-mod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.nosiphus.com/"
#logoFile="examplemod.png"
credits="MrCrayFish, Nosiphus, Ocelot"
authors="Nosiphus"
description='''
Nosiphus Furniture Mod is an addon to MrCrayFish's Furniture Mod that readds old furniture.
'''

[[mods]]
modId="cfm"
version="${mod_version}"
displayName="MrCrayFish's Furniture Mod"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.mrcrayfish.com/"
logoFile="furniture.png"
credits="The people who helped me when I first started creating mods. I wouldn't be here without them!"
authors="MrCrayFish, Nosiphus"
description='''
MrCrayfish's Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates. Ported by Nosiphus as part of Nosiphus Furniture Mod.
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="yogmod"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.cfm]]
modId="yogmod"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cfm]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cfm]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
